version: "1.0"
info:
  model: int-scaffold
packages:
- name: ExternalProject1Project
  gitServerName: rajka
  gitUrl: https://github.com/rajkapoor-rajkapoor
  gitUsername: rajkapoor-rajkapoor
  gitBranch: main
services:
- serviceName: project.externalproject1.ftp.connections:tesasas
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.http.connections:tweaas
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.integrations:Copy_test_Import
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.project.externalproject1.soap.connectors.TestSOpa_.connectors:GlobalWeatherSoap_GetWeather
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: pub.client:soapClient
  packages:
  - name: WmPublic
    version: 12.1.0.0.838
- serviceName: project.externalproject1.integrations:Coy_SoapConnecDAFservice
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.Custom_SoapCOnnector_.connectors:GlobalWeatherSoap_GetWeather
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.integrations:DAF
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 12.1.0.0.838
- serviceName: project.externalproject1.integrations:DAFUsingSMTPWithAttachedFile
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: pub.client:smtp
  packages:
  - name: WmPublic
    version: 12.1.0.0.838
- serviceName: project.externalproject1.integrations:HttpUsingCert
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 12.1.0.0.838
- serviceName: project.externalproject1.integrations:HttpsConnector
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.integrations:HttpsConnector8
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.integrations:NewSOap
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.TestSOpa_.connectors:GlobalWeatherSoap_GetWeather
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.integrations:SOapUsingWF
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.TestDeletion_.connectors:GlobalWeatherSoap_GetCitiesByCountry
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.integrations:SOap_PipelineValidation
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.integrations:Test
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.integrations:httpwithCert
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.integrations:test
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.integrations:test_Import
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.Custom_SoapCOnnector_.connectors:GlobalWeatherSoap_GetCitiesByCountry
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.Custom_SoapCOnnector_.responseServices:GlobalWeatherSoap_GetCitiesByCountry_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.Custom_SoapCOnnector_.responseServices:GlobalWeatherSoap_GetWeather_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.Custom_SoapCOnnector_.responseServices:genericFault_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.TestSOpa_.connectors:GlobalWeatherSoap_GetCitiesByCountry
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.TestSOpa_.responseServices:GlobalWeatherSoap_GetCitiesByCountry_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.TestSOpa_.responseServices:GlobalWeatherSoap_GetWeather_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.TestSOpa_.responseServices:genericFault_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.project.externalproject1.soap.connectors.TestSOpa_.connectors:GlobalWeatherSoap_GetCitiesByCountry
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.project.externalproject1.soap.connectors.TestSOpa_.responseServices:GlobalWeatherSoap_GetCitiesByCountry_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.project.externalproject1.soap.connectors.TestSOpa_.responseServices:GlobalWeatherSoap_GetWeather_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.project.externalproject1.soap.connectors.TestSOpa_.responseServices:genericFault_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
configurationVariables:
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
