version: "1.0"
info:
  model: int-scaffold
packages:
- name: ExternalProject1Project
  gitServerName: rajka
  gitUrl: https://github.com/rajkapoor-rajkapoor
  gitUsername: rajkapoor-rajkapoor
  gitBranch: main
- name: RestAPIUsingPackageService
  version: "1.0"
  gitServerName: rajka
  gitUrl: https://github.com/rajkapoor-rajkapoor
  gitUsername: rajkapoor-rajkapoor
  gitBranch: main
services:
- serviceName: project.externalproject1.integrations:Copy_DAFIUsingFF
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: pub.flatFile:convertToValues
  packages:
  - name: WmFlatFile
    version: 10.7.0.0.39
- serviceName: pub.flatFile:convertToString
  packages:
  - name: WmFlatFile
    version: 10.7.0.0.39
- serviceName: project.externalproject1.integrations:Copy_test_Import
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.project.externalproject1.soap.connectors.TestSOpa_.connectors:GlobalWeatherSoap_GetWeather
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: pub.client:soapClient
  packages:
  - name: WmPublic
    version: 12.1.0.0.1048
- serviceName: project.externalproject1.integrations:Coy_SoapConnecDAFservice
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.Custom_SoapCOnnector_.connectors:GlobalWeatherSoap_GetWeather
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.integrations:DAF
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 12.1.0.0.1048
- serviceName: project.externalproject1.integrations:DAFIUsingFF
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.integrations:DAFUsingSMTPWithAttachedFile
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: pub.client:smtp
  packages:
  - name: WmPublic
    version: 12.1.0.0.1048
- serviceName: project.externalproject1.integrations:FlatFile
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.integrations:HttpUsingCert
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 12.1.0.0.1048
- serviceName: project.externalproject1.integrations:HttpsConnector
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.integrations:HttpsConnector8
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: pub.client.ftp:ls
  packages:
  - name: WmPublic
    version: 12.1.0.0.1048
- serviceName: project.externalproject1.integrations:NewSOap
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.TestSOpa_.connectors:GlobalWeatherSoap_GetWeather
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.integrations:SOapUsingWF
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.TestDeletion_.connectors:GlobalWeatherSoap_GetCitiesByCountry
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.integrations:SOap_PipelineValidation
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.integrations:Test
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.integrations:TestFF
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.integrations:httpwithCert
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.integrations:test
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.integrations:test_Import
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.rad.TestImportRestAPIFromWMIO_.services:path_POST_1
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.Custom_SoapCOnnector_.connectors:GlobalWeatherSoap_GetCitiesByCountry
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.Custom_SoapCOnnector_.responseServices:GlobalWeatherSoap_GetCitiesByCountry_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.Custom_SoapCOnnector_.responseServices:GlobalWeatherSoap_GetWeather_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.Custom_SoapCOnnector_.responseServices:genericFault_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.TestSOpa_.connectors:GlobalWeatherSoap_GetCitiesByCountry
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.TestSOpa_.responseServices:GlobalWeatherSoap_GetCitiesByCountry_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.TestSOpa_.responseServices:GlobalWeatherSoap_GetWeather_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.TestSOpa_.responseServices:genericFault_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.aaaaaaaaaaaaaaa_.connectors:GlobalWeatherSoap_GetCitiesByCountry
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.aaaaaaaaaaaaaaa_.connectors:GlobalWeatherSoap_GetWeather
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.aaaaaaaaaaaaaaa_.responseServices:GlobalWeatherSoap_GetCitiesByCountry_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.aaaaaaaaaaaaaaa_.responseServices:GlobalWeatherSoap_GetWeather_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.aaaaaaaaaaaaaaa_.responseServices:genericFault_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.asasaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_.connectors:GlobalWeatherSoap_GetCitiesByCountry
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.asasaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_.connectors:GlobalWeatherSoap_GetWeather
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.asasaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_.responseServices:GlobalWeatherSoap_GetCitiesByCountry_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.asasaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_.responseServices:GlobalWeatherSoap_GetWeather_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.externalproject1.soap.connectors.asasaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_.responseServices:genericFault_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.project.externalproject1.soap.connectors.TestSOpa_.connectors:GlobalWeatherSoap_GetCitiesByCountry
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.project.externalproject1.soap.connectors.TestSOpa_.responseServices:GlobalWeatherSoap_GetCitiesByCountry_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.project.externalproject1.soap.connectors.TestSOpa_.responseServices:GlobalWeatherSoap_GetWeather_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
- serviceName: project.project.externalproject1.soap.connectors.TestSOpa_.responseServices:genericFault_Response
  packages:
  - name: ExternalProject1Project
    version: "1.0"
  - name: RestAPIUsingPackageService
    version: "1.0"
configurationVariables:
  jdbc.SAP TxStore Pool.maxConns: "10"
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbc.SAP TxStore Pool.poolThreshold: "0"
  jdbc.SAP TxStore Pool.dbURL: jdbc:mysql://adapter-mysql-80-on-amazonrds.cdmjexwbzoym.us-east-1.rds.amazonaws.com:3306/SAPTRANSACTIONSTORE?useSSL=false&characterEncoding=utf-8&autoReconnect=true&maxReconnects=5&sessionVariables=wait_timeout=2147483
  jdbc.SAP TxStore Pool.spyenabled: "false"
  jdbc.SAP TxStore Pool.useSSL: "false"
  jdbc.SAP TxStore Pool.waitingThread: "10"
  jdbc.SAP TxStore Pool.description: Connection Pool for the SAP Transaction Store
  jdbc.SAP TxStore Pool.password: "{AES}7EzrljL+N3kbQseeO6Awng=="
  jdbc.SAP TxStore Pool.spyparms: SpyAttributes=(log=(file)logs/spy/SAP_TxStore_Pool.log;logTName=yes;timestamp=yes)
  jdbc.SAP TxStore Pool.snoopenabled: "false"
  jdbc.SAP TxStore Pool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/SAP_TxStore_Pool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.SAP TxStore Pool.expireTime: "60000"
  jdbc.SAP TxStore Pool.minConns: "5"
  jdbc.SAP TxStore Pool.userid: sapuser
  jdbc.SAP TxStore Pool.driverAlias: MySQL CC Driver
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
