version: "1.0"
info:
  model: int-scaffold
packages:
- name: ExternalProject1Project
  gitServerName: rajka
  gitUrl: https://github.com/rajkapoor-rajkapoor
  gitUsername: rajkapoor-rajkapoor
  gitBranch: main
services:
- serviceName: project.externalproject1.http.connections:HttoConnectorUsingCert
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.integrations:DAF
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 12.1.0.0.826
- serviceName: project.externalproject1.integrations:DAFUsingSMTPWithAttachedFile
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: pub.client:smtp
  packages:
  - name: WmPublic
    version: 12.1.0.0.826
- serviceName: project.externalproject1.integrations:HttpUsingCert
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 12.1.0.0.826
- serviceName: project.externalproject1.integrations:HttpsConnector
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.integrations:HttpsConnector8
  packages:
  - name: ExternalProject1Project
    version: "1.0"
- serviceName: project.externalproject1.integrations:Test
  packages:
  - name: ExternalProject1Project
    version: "1.0"
