version: "1.0"
projectName: ExternalProject1Project
runtimes:
- runtimeAlias: Cloud Designtime
  assets:
  - name: Test
    type: workflow
    uid: flfada7220a6224086b78c7c9f923b47d4
    stepId: a0
    reference: project.externalproject1.integrations:HttpsConnector
  - name: fld_131297913_stage00.projects.flede9297a13fc4be58ac383aa0a8410fb.integrations:TestPS
    type: flow
    stepId: /0
    reference: fld_131297913_stage00.projects.flede9297a13fc4be58ac383aa0a8410fb.WmPackageServiceProvider.project.externalproject1.integrations:test_Import
  - name: RestAPI
    type: REST
    path: /DAF
    action: PUT
    reference: fld_131724708_stage00.projects.fla6f18e5fbc6044d491add1132272ee21.WmPackageServiceProvider.project.externalproject1.integrations:SOapUsingWF
- runtimeAlias: IC_RajkapoorRestAPI
  assets:
  - name: RestAPIClientIngress
    type: DAF
  - name: RestAPI
    type: REST
    path: /DAF
    action: GET
    reference: fld_131724708_stage00.projects.fla6f18e5fbc6044d491add1132272ee21.WmPackageServiceProvider.project.externalproject1.integrations:HttpUsingCert
- runtimeAlias: Cloud Runtime
  assets:
  - name: RestAPI
    type: REST
    path: /DAF
    action: POST
    reference: fld_131724708_stage00.projects.fla6f18e5fbc6044d491add1132272ee21.WmPackageServiceProvider.project.externalproject1.integrations:FlatFile
